### ISSUE TITLE
Bad performance on human data

### ISSUE THREAD

**Issue by JunyuanDeng** [google-research/sparf#10]
Hello, thanks for your great job!

I tested the PCD-net with human take from 2 cameras, but the results seem to be quite bad, could you please help me to improve it?

Here is my result:
![Screenshot from 2023-10-07 17-17-08](https://github.com/google-research/sparf/assets/62542727/591857bb-e11f-40b4-9b77-db203bf52d48)

**Comment by PruneTruong** [comment]
Hi, 

PDC-Net was trained on outdoor data, which shows different image content but also very different transformation types than yours, so it's not so surprising that it doesn't perform well on human data. I think it would need to be retrained for these kinds of scenes with 3d data. You might want to try other matching networks, SPARF can be used with any matches. I am not very familiar with human-related literature, but usually, it is my impression that they have separate human-specific networks for everything. There might exist a matching network specifically trained for human data.

**Comment by JunyuanDeng** [comment]
Thanks for your reply!
