### ISSUE TITLE
NaN in Rays

### ISSUE THREAD

**Issue by FelTris** [google-research/sparf#11]
Hi, thanks for the cool work! 
I think I know where the NaNs in the ray computation come from. For the LLFF dataloader if the bounds.min() is zero the scale factor will be divided by zero and therefore also the translational component of the poses will be scaled with this NaN value. 
At least that was the case when I tried it on some custom data. 
Hope this helps some people!

**Comment by PruneTruong** [comment]
Hi, 

Thanks for letting me know! I don't think I have encountered this issue in my trainings, but it's good to know for other.
