### ISSUE TITLE
There is no definition and implementation of the function "render_by_slices_w_custom_rays"

### ISSUE THREAD

**Issue by yuanjie0217** [google-research/sparf#12]
This function appears in the source/models/render.py file, but I did not find the implementation code of this function

**Comment by PruneTruong** [comment]
Hi you are right, however I don't think this is being called anywhere, I could run the code fine

**Comment by PruneTruong** [comment]
I removed the calls to render_by_slices_w_custom_rays for clarity. Thanks for pointing this out.
