### ISSUE TITLE
Laggy When Running

### ISSUE THREAD

**Issue by TwiceMao** [google-research/sparf#14]
@PruneTruong  Hi，thx for your awesome work. I have 48 1200*680 color images and want to compare them with your paper. However, when running your code, the GPU is out of memory during image matching. It seems that your feature matching is all-to-all. Can you give me some advice?

**Comment by PruneTruong** [comment]
Hi, you can change the batch size for the matching computation here: s://github.com/google-research/sparf/blob/main/train_settings/default_config.py#L192.
