### ISSUE TITLE
Error running "python third_party/test_pdcnet_installation.py"

### ISSUE THREAD

**Issue by jexiaong** [google-research/sparf#5]
I'm currently getting an error when I run `python third_party/test_pdcnet_installation.py`
![image](https://github.com/google-research/sparf/assets/114371159/95943005-8d2e-4561-85d7-776af09c7496)

**Comment by PruneTruong** [comment]
Hi, this seems related to the numpy version you are using. To avoid this, I would suggest installing the packages with the same versions than I had, i.e. with requirements_w_version.txt.

**Comment by PruneTruong** [comment]
This should be python=3.7 or 3.8, sorry about that, I will update. Let me know if that works.

**Comment by jexiaong** [comment]
I'm still having some trouble with installing some of the requirements. I am using Cuda 11.3 NVIDIA GeForce RTX 3080 Ti
From requirements_w_version.txt, I could not install any of `scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1640464152916/work`, `scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1637806658031/work`, and `Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1645323161513/work`
Also, there was no matching distribution for `open3d==0.15.2` (so I changed it to 0.15.1), `pycolmap==0.3.0` (and there were no other versions to choose from so I deleted it from the file), and I removed the version specification for oryx.
Furthermore, I got this error 
![image](https://github.com/google-research/sparf/assets/114371159/1f6977d5-fe1f-4b91-b42d-98dd63fb5bf2)
however the version 1.10.2 does exist among the available versions, so I deleted the +cu113 off the all the torch requirements. I don't know why I couldn't include the +cu113?
This is the resulting requirements file
![image](https://github.com/google-research/sparf/assets/114371159/1d952d02-6b05-479e-b075-8a4ec97f0887)
I don't know how any of these changes will affect anything down the line though. 
Do you have any insight regarding why I can't install these specific requirements? Sorry for all the issues I'm relatively new to this >.<

*edit: when I run `python third_party/test_pdcnet_installation.py`, I get the error raise `AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled` Is this because I removed the +cu113? But I was unable to install +cu113?

**Comment by jexiaong** [comment]
Ignore the previous message, I was running on Windows this whole time and I didn't realize it wasn't supported so now I'm on wsl

**Comment by jexiaong** [comment]
Sorry, another question, I'm currently running into torch.cuda.OutOfMemoryError when I train the images. I noticed you used a A100 (or V100) GPU with 20GB of memory; however, I'm using a NVIDIA GeForce RTX 3080 Ti with 12GB of memory. I was wondering if the error is caused by a limitation in hardware or should the program still work as expected? Would debugging methods such as reducing batch size/precision be helpful or should I expect the program not to work with my current hardware?

**Comment by PruneTruong** [comment]
Hi, you need to change the number of rays sampled per iteration, by changing the config.rand_rays
