### ISSUE TITLE
Questions about batch setting and out of memory.

### ISSUE THREAD

**Issue by yfqi** [google-research/sparf#8]
I have a question: When I train my own dataset with joint_pose_nerf_training and train_sub = 6, it works fine. However when I train the network with nerf_training_w_gt_poses and train_sun=6, it shows out of memory. 
So:
1. I wonder what differences about dataloaders between them two and what I can do to solve it. 
2. I also wonder how I can set the batches in your networks. Thank you

**Comment by PruneTruong** [comment]
Hi, 

That is a bit strange, the dataloaders should be the same. I will check what could be different. 
As for the batches, you need to change config.rand_rays in the configs and reduce that number.

**Comment by yfqi** [comment]
您好，来信已收到，感谢您的邮件。

**Comment by yfqi** [comment]
您好，来信已收到，感谢您的邮件。
